### PR TITLE
Cleanups/chmod gitignore

### PR DESCRIPTION
**Pull request by Quix0r**
This PR ignores all torrent files as they should never be committed and also `libs/db.php` as it contains sensitive infomations. This also fixes CHMOD. Only scripts that should be run from shell must have execute flag set, all others not. The server does **not** execute PHP scripts, it only _reads_ them.

### CODE REVIEW

**Comment by Quix0r** [comment]
The 2nd commit removes my added `error_reporting(0);` commands again as your script issues many E_NOTICE. Please fix them all: `error_reporting(E_ALL | E_STRICT);` is generally only for development environments `0` for productive servers.

**Comment by Quix0r** [comment]
And yeah, my changes remove external references as it is generally not a good idea to have them around.

**Comment by atmoner** [comment]
@Quix0r Thank you for your work! I will test all this when I go home and if it works without error I would validate the push

**Comment by atmoner** [comment]
@Quix0r I am not against the modification of the check of the install! But the user should be warned to create a db.php file (in install.php).
And thanks for the missing javascript file!

**Comment by Quix0r** [comment]
Okay, then better mention that change in readme file.

**Comment by Quix0r** [comment]
Should I add it or do you add it?

**Pull request merged**
