### PR TITLE
Change constructor function

### PR DESCRIPTION
**Pull request by Kcchouette**
As the primary constructor function is depreciated

Please DO NOT merge yet

### CODE REVIEW

**Comment by atmoner** [comment]
Hello @Kcchouette =)
Sorry for delay!! I take over the project 100%

For this pull, Are you sure of your shot?
Thanks =)

**Comment by Kcchouette** [comment]
Hello @atmoner, yes: https://stackoverflow.com/a/36340079

**Comment by Kcchouette** [comment]
You should to do that for all your class, it's why I put "do not merge yet" (but I forgot to finish this PR :/)

**Comment by atmoner** [comment]
@Kcchouette Nice!!! Let me do some testing =) 

Off:
I put the domain online, if you have plugins, could you put them on the forum?
I'm really sorry but I lost all my backups! (really everything except the github)

**Comment by Kcchouette** [comment]
Sorry I keep nothing :/
Tbh I though you've abandoned this project :/

**Comment by atmoner** [comment]
At the time of giving up the domain name, I could not do it .... So I renew the domain name and I crack!
I made a lot of modifications these last days! Especially safe level !!

I also updated the system of plugins, everything works on php7
I just need to create new plugins / themes ....

**Comment by atmoner** [comment]
Done for me!! Thanks =)

**Pull request merged**
